"""empty message

Revision ID: ca7f8f90b2a8
Revises: fddb59391dfb
Create Date: 2019-04-22 19:35:12.855275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7f8f90b2a8'
down_revision = 'fddb59391dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friends_name_key', 'friends', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('friends_name_key', 'friends', ['name'])
    # ### end Alembic commands ###
